### ISSUE TITLE
您好，这个项目还在做吗？

### ISSUE THREAD

**Issue by progss** [zhang8043/AgileWork#4]

**Comment by zhang8043** [comment]
在做的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月21日(周五) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhang8043/AgileWork] 您好，这个项目还在做吗？ (Issue #4)

**Comment by triangle959** [comment]
已收到

**Comment by effapp** [comment]
这个项目似乎很久没有更新了，作者是放弃更新了吗？
